title: "Atius"
description: "I make videos, and sometimes write article"
permalink: /:title/
theme-color: "#006fff"
gravatar: d43980d430448a2c84749b82af8eb76a


mastodon: atius@firefish.social

authors:
  atius:
    name: Atius
    description: "someone I imagined"
    gravatar: d43980d430448a2c84749b82af8eb76a # Gravatar md5 hash
  anonymous:
    name: "WHO????"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

paginate: 7
paginate_path: "/archive/:num/"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

future: false # Allows us to stage posts
exclude: [README.md, Gemfile, Gemfile.lock, vendor]
